### ISSUE TITLE
Javascript Ninja

### ISSUE THREAD

**Issue by felipedotcom** [felipedotcom/WorkFlow#5]
## AULA 01
- [x] Introdução
- [x] Variáveis e tipos de dados
- [x] Operadores aritméticos
- [x] Operadores de igualdade e relacionais
- [x] Funções
- [x] Desafio da semana 01  

## AULA 02

- [x] Revisão Desafio da semana 01
- [x] Operadores Lógicos
- [x] Operadores Unários
- [x] Estrutura Léxica
- [x] Instruções condicionais - IF
- [x] Desafio da semana #02  

## AULA 03

- [x]  Revisão do desafio da semana 02 - Parte 1
- [x] Revisão do desafio da semana 02 - Parte 2
- [x] Revisão do desafio da semana 02 - Parte 3
- [x] Tipos de dados e objetos 
- [x] Métodos de objeto 
- [x] Métodos de objeto (continuação) e desafio da semana #03  

## AULA 04  

- [x] Revisão do desafio da semana 03 - Parte 1  
- [x] Revisão do desafio da semana 03 - Parte 2 
- [x] Truthy e Falsy
- [x] Condicional Ternário 
- [x] Escopo de variáveis e funções 
- [x] Desafio da semana #04

## AULA 05

- [x] Revisão do desafio da semana #04 - Parte 1 
- [x] Revisão do desafio da semana #04 - Parte 2 
- [x] Revisão do desafio da semana #04 - Parte 3 
- [x] Retorno de funções com arrays e objetos
- [x] Parâmetros de Funções como arrays e objetos 
- [x] Desafio da semana #05

## AULA 06 

- [x] Revisão Desafio da semana #05 - Parte 1 
- [x] Revisão Desafio da semana #05 - parte 2
- [x] Revisão Desafio da semana #05 - parte 3 
- [x] Revisão Desafio da semana #05 - parte 4 
- [x] Operador virgula e estrutura condicional switch
- [x] Estrutura de repetição While e desafio da semana #06

## AULA 07

- [x] Revisão do desafio da semana #06 - Parte 1 
- [x] Revisão do desafio da semana #06 - Parte 2 
- [x] O operador módulo 
- [x] Arrays - a propriedade length 
- [x] Arrays - método "push()" e Loop "for" 
- [x] Desafio da semana #07

## AULA 08

- [x] Revisão Desafio semana #07 
- [x] A importância de nomear funções 
- [x] Introdução à Functional Programming 
- [x] Functional Programming - parte 2 
- [x] Functional Programming - parte 3 
- [x] Desafio da semana #08 

## AULA 09 

- [x] Revisão desafio semana #08 - Parte 1 
- [x] Revisão desafio semana #08 - Parte 2 
- [x] Escopo de funções 
- [x] hoisting 
- [x] IIFE - Immediately-Invoked Function Expression 
- [x] Desafio semana #09

## AULA 10 

- [x] Revisão desafio da semana #09 - Parte 1 
- [x] Revisão desafio da semana #09 - Parte 2 
- [x] Revisão desafio da semana #09 - Parte 3 
- [x] Wrapper Objects 
- [x] typeof 
- [x] Desafio da semana #10

## AULA 11

- [x] Revisão desafio semana #10 - Parte 1 
- [x] Revisão desafio semana #10 - parte 2 
- [x] Revisão desafio semana #10 - parte 3
- [x] Laços (Loops) 
- [x] Saltos 
- [x] Desafio semana #11

## AULA 12

- [x] Revisão desafio semana #11 - Parte 1 
- [x] Revisão desafio semana #11 - parte 2 
- [x] Criação de objetos 
- [x] Criação de objetos - Object.create 
- [x] Métodos de objeto 
- [x] Arrays - Métodos 

## AULA 13

- [x] Revisão desafio semana #12 - Parte 1 
- [x]  Revisão desafio semana #12 - Parte 2 
- [x] Arrays - toString, concat, unshift e shift 
- [x] slice e splice 
- [x] forEach, every, some 
- [x] map, filter e desafio da semana #13 

## AULA 14 

- [x] Revisão do desafio da semana #13 - Parte 1 
- [x] Revisão do desafio da semana #13 - parte 2 
- [x] Revisão do desafio da semana #13 - parte 3 
- [x]  reduce() e reduceRight() 
- [x] indexOf(), lastIndexOf() e isArray() 
- [x] Desafio da semana #14 

## AULA 15 

- [x] Revisão do desafio da semana #14 - Parte 1 
- [x] Revisão do desafio da semana #14 - parte 2 
- [x]  Revisão do desafio da semana #14 - parte 3 
- [x] JS no browser 
- [x] O objeto this 
- [x] Objeto arguments e desafio da semana #15 

## AULA 16 

- [x]  Revisão desafio da semana #15 
- [x] use strict - Criação de variáveis sem o "var"  
- [x] use strict - uso do with e global this === undefined 
- [x] use strict - o operador delete, objetos e funções 
- [x] Objeto String 
- [x] Objeto String - parte 2 e desafio da semana #16 

## AULA 17

- [x] Revisão do desafio da semana #16 - parte 1 
- [x] Revisão do desafio da semana #16 - parte 2 
- [x] Revisão do desafio da semana #16 - parte 3 
- [x] Regex - Parte 1 
- [x] Regex - parte 2 
- [x] Regex - parte 3 

## AULA 18

- [x] Revisão desafio da semana #17 - Parte 1 
- [x] Revisão desafio da semana #17 - parte 2 
- [x] Revisão desafio da semana #17 - parte 3 
- [x] Continuação de Regex 
- [x] Regex - Negação 
- [x] Regex - Repetidores 

## AULA 19 

- [x] Revisão do desafio da semana #18 - Parte 1 
- [x] Revisão do desafio da semana #18 - parte 2 
- [x] Revisão do desafio da semana #18 - parte 3 
- [x] Conhecendo outros símbolos usados na Regex 
- [x] Métodos de string onde podemos usar regex 
- [x] O objeto RegExp() 

## AULA 20

- [x] Revisão do desafio da semana #19 - Parte 1 
- [x] Revisão do desafio da semana #19 - parte 2 
- [x] JS no browser - Selecionar elementos do DOM 
- [x] JS no browser - parte 2 
- [x] JS no browser - parte 3 - Selecionando elementos do DOM 
- [x] JS no browser - parte 4 - Formulários e eventos 

## AULA 21
 
- [x] Revisão do desafio da semana #20 - Parte 1 
- [x] Revisão do desafio da semana #20 - parte 2 
- [x] Revisão do desafio da semana #20 - parte 3 
- [x] Sync vs async 
- [x] setTimeout 
- [x] setTimeout vs setInterval 

## AULA 22 

- [x] Revisão do desafio da semana #21 - Parte 1 
- [x] Revisão do desafio da semana #21 - parte 2 
- [x] Propriedades e métodos de funções - parte 1 
- [x] Propriedades e métodos de funções - parte 2 
- [x] Prototype 
- [x] Array-like, editorconfig e desafio da semana #22 

## AULA 23 

- [x] Revisão do desafio da semana #22 - Parte 1 
- [x] Revisão do desafio da semana #22 - parte 2 
- [x] Debug - parte 1 
- [x] Debug - parte 2 
- [x] Debug - parte 3 
- [x] Debug - parte 4

## AULA 24 

- [x] Revisão do desafio da semana #23 
- [x] Modularização de código - parte 2 
- [x] Modularização de código - parte 3 
- [x] Modularização de código - parte 4 
- [x] Modularização de código - parte 5  
- [x] Modularização de código - parte 6 

## AULA 25 

- [x] Revisão do desafio da semana #24 - Parte 1 
- [x] Revisão do desafio da semana #24 - parte 2 
- [x] Revisão do desafio da semana #24 - parte 3 
- [x] Scripts e eventos inline 
- [x] Eventos 
- [x] Mais eventos por elemento 
 
## AULA 26 

- [x] O que é DOM e como percorrer os elementos da árvore 
- [x] Percorrer DOM - Propriedades - parte 1 
- [x] Percorrer DOM - Propriedades - parte 2 
- [x] Percorrer DOM - Métodos - parte 1 
- [x] Percorrer DOM - Métodos - parte 2 
- [x] Percorrer DOM - Atributos 

## AULA 27 

- [x] Revisão desafio da semana #26 - Parte 1
- [x] Revisão desafio da semana #26 - Parte 2 
- [x] Revisão desafio da semana #26 - Parte 3 e DOM Fragments 
- [x] Eventos 
- [x] Técnicas Ninja 
- [x] Desafio da semana #27

## AULA 28 

- [x] Revisão desafio da semana #27 - Parte 1 
- [x] Revisão desafio da semana #27 - Parte 2 
- [x] Introdução à Ajax 
- [x] Ajax - Parte 2 
- [x] Ajax - Parte 3 
- [x] Ajax - Parte 4, try/catch e desafio da semana #28 

## AULA 29 

- [x] Revisão desafio da semana #28 - Parte 1 
- [x] Revisão desafio da semana #28 - Parte 2 
- [x] Revisão desafio da semana #28 - Parte 3 
- [x] Revisão desafio da semana #28 - Parte 4 
- [x] Module Pattern 
- [x] Module Pattern - parte 2 e desafio da semana #29 

## AULA 30 

- [x] Revisão desafio da semana #29 - Parte 1 
- [x] Revisão desafio da semana #29 - Parte 2 
- [x] Revisão desafio da semana #29 - Parte 3 
- [x] Revisão desafio da semana #29 - Parte 4 
- [x] Revisão desafio da semana #29 - Parte 5 
- [x] Module Pattern - closure e desafio #30

## AULA 31 

- [ ] DOM - innerHTML
- [ ] DOM - innerHTML - Problemas de segurança 
- [ ] DOM - insertAdjacentHTML 
- [ ] O objeto Date 
- [ ] O objeto Date - Propriedades e métodos 
- [ ] Conhecendo o objeto Math 

## AULA 32 

- [ ] Ajax 
- [ ] REST Api 
- [ ] REST Api - Cors 
- [ ] Ajax - sync - POST 
- [ ] Ajax - POST - Parte 2 
- [ ] Ajax - POST - Parte 3 

## AULA 33 

- [ ] Testes 
- [ ] Escrevendo os primeiros testes 
- [ ] Entendendo o escopo Red - Green - Blue 
- [ ] Escrevendo mais testes 
- [ ] TDD Style 
- [ ] Documentação do Mocha e Code Coverage

## AULA 34 

- [ ] Introdução 
- [ ] Uglify.js - parte 1 
- [ ] Uglify.js - parte 2 
- [ ] Sourcemaps 
- [ ] Diferenças entre console.log e return 
- [ ] Objetos e encerramento
